### ISSUE TITLE
Select arround tag

### ISSUE THREAD

**Issue by m1guer** [jellydn/zed-101-setup#20]
### Describe the bug

after use the cfgs i faced an error: select arround tag/select inside tag and others options are not working.

### Reproduction

paste the cfgs

### System Info

```Shell
System:
    OS: Linux 6.10 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 4500 6-Core Processor
    Memory: 6.59 GB / 15.42 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
I believe this is a bug. Please open on upstream report. Thanks.
