### ISSUE TITLE
vim mode blank page not work

### ISSUE THREAD

**Issue by reaink** [jellydn/zed-101-setup#7]
### Describe the bug
space sapce not response

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/92ea00e1-4080-443c-b2d2-b7e3bfcc1cfe">

### Reproduction

open zed editor, close all files

### System Info

```Shell
macos  Zed 0.143.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
Yeah, I noticed this issue as well. Only works if you open at least 1 file. Let's see if Zed team will fix this. Thanks.

**Comment by jellydn** [comment]
FYI - Fixed by this mapping https://github.com/jellydn/zed-101-setup/commit/dad267416a29d2a798ac75b0b4fa01b553f1bda2
